network="dev"
miner-enabled=true
miner-coinbase="0xfe3b557e8fb62b89f4916b721be55ceb828dbd73"
rpc-http-cors-origins=["all"]
host-whitelist=["*"]
rpc-ws-enabled=true

min-gas-price=0

rpc-http-enabled=true
rpc-http-port=8545
rpc-http-api=["ETH","IBFT","CLIQUE","DEBUG","MINER","NET","PERM","ADMIN","EEA","TXPOOL","PRIV","WEB3"]

# RPC HTTP TLS Settings
rpc-http-tls-enabled=true
rpc-http-tls-keystore-file="./keystore/keystore.pfx"
rpc-http-tls-keystore-password-file="./keystore/password.txt"
rpc-http-tls-client-auth-enabled=true
rpc-http-tls-known-clients-file="./keystore/knownClients.txt"
rpc-http-tls-ca-clients-enabled=false

# Privacy related options
privacy-enabled=true
privacy-url="https://127.0.0.1:8888"
privacy-public-key-file="./orion/nodeKey.pub"

# Privacy TLS Options
privacy-tls-enabled=true
privacy-tls-keystore-file="./orion/keystore/keystore.pfx"
privacy-tls-keystore-password-file="./keystore/password.txt"
privacy-tls-known-enclave-file="./orion/keystore/knownServers.txt"

data-path="./data"