network="dev"
miner-enabled=true
miner-coinbase="0xfe3b557e8fb62b89f4916b721be55ceb828dbd73"
rpc-http-cors-origins=["all"]
host-whitelist=["*"]
rpc-ws-enabled=true

rpc-http-enabled=true
rpc-http-port=8545
rpc-http-api=["ETH","IBFT","CLIQUE","DEBUG","MINER","NET","PERM","ADMIN","EEA","TXPOOL","PRIV","WEB3"]

# RPC HTTP TLS Settings
rpc-http-tls-enabled=true
rpc-http-tls-keystore-file="./keystore/besu_keystore.pfx"
rpc-http-tls-keystore-password-file="./keystore/besu_ks_password.txt"
rpc-http-tls-client-auth-enabled=true
rpc-http-tls-known-clients-file="./trust/besu_known_clients.txt"
rpc-http-tls-ca-clients-enabled=false

data-path="./data"